const reindeer = [
  {name: 'Dasher',
  activeYears: 1865,
  personality: ["social", "likes the cold", "party-animal", "happy"],
  bio: "Dasher is the hardest worker of Santa's reindeer. He is strong and known to be very fast. This may be due to his love for munching on carrots or grazing the grass outside the barn, but even in the off season Dasher is seen training every day in order to fly that sleigh on Christmas Eve.",
},
{name: 'Dancer',
  activeYears: 1865,
  personality: ["dancing", "colorful", "popular", "loves popcorn"],
  bio: "Dancer is a reindeer with a unique personality. He's completely extroverted. When he's not helping Santa, he's having dance parties. His favorite genre is Latin music due to the strong rhythm.",
},
{name: 'Prancer',
  activeYears: 1695,
  personality: ["always looks good", "great baker", "very loyal", "enthusiastic"],
  bio: "Prancer loves the other reindeer and would do anything for them. But he also loves to carry a mirror to gaze at himself on the sleigh every now and then. He has to look his best all the time because he never knows quite who he’s going to meet. He often is found in the elves’ factory prancing around gracefully with all the other reindeer, elves, and helpers cheering him on.",
},
{name: 'Vixen',
  activeYears: 1695,
  personality: ["very smart", "cool, calm, collected", "trickster", "helpful"],
  bio: "Vixen is the comedic reindeer known for lots of magic tricks. The other reindeer often get slightly annoyed with his ability to make things disappear and reappear. He’s great at tricking the other reindeer out of their candy canes. He also has a weakness for yummy Santa-shaped chocolates. Santa loves Vixen’s tricks because they really come in handy on Christmas Eve. That bag of toys is quite large, and that chimney is quite small . . .",
},
{name: 'Comet',
  activeYears: 1673,
  personality: ["jokester", "athletic", "laid back", "determined"],
  bio: "Comet is out of this world—as his name implies. He’s quite handsome and is always smiling. He’s easy-going and loves to play ball with all the young fawns. In the days before Christmas, Santa will head out with Comet to check his list and see how children all around the world are doing. When they see Comet, they flock to pet him because he’s quite adorable and so laid-back. He just loves the attention the children shower upon him. Plus, he inspires little children to be on their best behavior.",
},
{name: 'Cupid',
  activeYears: 1667,
  personality: ["very romantic", "affectionate", "loves jazz music", "archery"],
  bio: "Cupid is an affectionate reindeer. She has Christmas reins decorated with red and green little heart-shaped bells. Her motto is “Spread the Love.” She often carries mistletoe sprigs and mysteriously places them all around peoples’ entryways at Christmastime. That way, people don’t forget to hug and kiss during the season. She’s always singing.",
},
{name: 'Donder',
  activeYears: 1580,
  personality: ["powerful leader", "loves to sing", "very creative", "loves dark chocolate"],
  bio: "Donner’s name comes from “thunder” in German. This is for good reason. He’s always noticed when entering a room because he’s got a deep, booming baritone voice. He loves to sing those low notes. He loves hanging out with Blitzen, too. Together, they can really belt out some dynamic duets.",
},
{name: 'Blitzen',
  activeYears: 1580,
  personality: ["fast worker", "loves watching movies", "always on time", "spontaneous"],
  bio: "Blitzen’s name comes from the German word for 'lightning.' He is fast, playful, and flies like a bolt when it comes to helping Santa deliver his Christmas goodies. He is also best reindeer-buds with Donner, and they often hum duets to themselves while flying high in the skies.",
},
{name: 'Rudolph',
  activeYears: 81,
  personality: ["humble", "sometime shy", "loves reindeer games", "willing to take charge"],
  bio: "Rudolph is Santa’s famous ninth reindeer. He joined the herd a few years after the original eight. At first, he was terribly self-conscious. He suffered from low self-esteem because he had an odd red nose. It wasn’t until Santa recognized his rosy bulb as a beacon of light that he was ushered into his role as leader of the herd. Because his nose glowed, he was able to lead Santa safely around the world, on the snowiest of nights . . . and the other reindeer agreed that Rudolph just had to stay with the herd. Now, when Rudolph isn’t helping on the sleigh ride, he loves to play hide-and-seek with the other reindeer. He has an advantage, though. He can light up dark places effortlessly and find the other reindeer every time.",
},
]